import "./globals.css";
import { Metadata } from "next";
import PathAwareWrapper from "../components/PathAwareWrapper";

export const metadata: Metadata = {
  title: "Epic Game",
  description: "Generated by Mr. Umar",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <body className="bg-app-secondary ">
        <PathAwareWrapper>{children}</PathAwareWrapper>
       
      </body>
    </html>
  );
}
 
