import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "@/src/components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Epic Game",
  description: "Generated by Mr. Umar",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}  bg-app-secondary antialiased `} suppressHydrationWarning
      >
       
        <Header />
        <main className=" w-full max-w-5xl mx-auto ">{children}</main>
       <div className="max-w-5xl mx-auto  border-t border-text-clr  w-full text-white flex py-10 bg-app-secondary">
        {" "}
        <h5 className="text-white text-xs">
          * The lowest price offered on The Epic Games Store in the last 30 days
          before discount
        </h5>
      </div>
      </body>
    </html>
  );
}
